### PR TITLE
Edited for Teensyduino 1.42

### PR DESCRIPTION
**Pull request by DJQuardaboff**

### CODE REVIEW

**Comment by zlittell** [comment]
I will review these files over the next couple of days and merge this request.  Your work is appreciated!

**Comment by Matteoson** [comment]
@DJQuardaboff thanks for the update i'm using Teensyduino 1.42 with your updated code but get the following compile errors 


C:\MVMDRIVE\VX1\TOOLS\arduino-1.8.5\hardware\teensy\avr\cores\teensy3\xinput.cpp: In member function 'void XINPUT::sendXinput()':

C:\MVMDRIVE\VX1\TOOLS\arduino-1.8.5\hardware\teensy\avr\cores\teensy3\xinput.cpp:299:2: error: 'XInputUSB' was not declared in this scope

  XInputUSB.send(TXData, USB_TIMEOUT);

  ^

C:\MVMDRIVE\VX1\TOOLS\arduino-1.8.5\hardware\teensy\avr\cores\teensy3\xinput.cpp: In member function 'uint8_t XINPUT::receiveXinput()':

C:\MVMDRIVE\VX1\TOOLS\arduino-1.8.5\hardware\teensy\avr\cores\teensy3\xinput.cpp:310:6: error: 'XInputUSB' was not declared in this scope

  if (XInputUSB.available() > 0)

      ^

**Comment by DJQuardaboff** [comment]
Did you switch the USB type to XInput?
Maybe try moving `xinput.h` and `xinput.cpp` to the same directory as your `.ino` file.
(don't forget to change the angle brackets to quotes on the include statement)

**Comment by Matteoson** [comment]
Yes thank you worked once i set the USB type to Xinput! thanks wonderful.

**Comment by dmadison** [comment]
Why combine the XInput keywords with the Teensy keywords? That just makes another file to fight conflicts with when updating.

**Comment by DJQuardaboff** [comment]
I realize now that the keywords describe the `xinput.h` and not `usb_xinput.h`

I changed it back:
DJQuardaboff@206bdbc47c0711ed0e84c046129748588e67263a

**Comment by zlittell** [comment]
This has finally been done.  Sorry for the delay!

**Pull request merged**
